-- MySQL Script generated by MySQL Workbench
-- Sat Aug  5 15:31:40 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ssm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ssm` ;

-- -----------------------------------------------------
-- Schema ssm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssm` DEFAULT CHARACTER SET utf8 ;
USE `ssm` ;

-- -----------------------------------------------------
-- Table `ssm`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`orders` ;

CREATE TABLE IF NOT EXISTS `ssm`.`orders` (
  `id_orders` INT NOT NULL AUTO_INCREMENT,
  `orders_remark` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `orders_countprice` INT NOT NULL,
  `orders_states` VARCHAR(45) NOT NULL DEFAULT 'open',
  `orders_mid` INT NULL,
  `orders_uid` INT NULL,
  `orders_date` INT NOT NULL,
  PRIMARY KEY (`id_orders`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ssm`.`shopcar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`shopcar` ;

CREATE TABLE IF NOT EXISTS `ssm`.`shopcar` (
  `id_shopcar` INT NOT NULL AUTO_INCREMENT,
  `shopcar_itemname` VARCHAR(255) NULL,
  `shopcar_itemprice` INT NULL,
  `shopcar_itemnum` INT NULL,
  `shopcar_adddate` INT NOT NULL,
  `shopcar_uid` INT NOT NULL,
  `orders_id_orders` INT NOT NULL,
  PRIMARY KEY (`id_shopcar`),
  INDEX `fk_shopcar_orders1_idx` (`orders_id_orders` ASC),
  CONSTRAINT `fk_shopcar_orders1`
    FOREIGN KEY (`orders_id_orders`)
    REFERENCES `ssm`.`orders` (`id_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ssm`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`users` ;

CREATE TABLE IF NOT EXISTS `ssm`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(60) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `user_address` VARCHAR(255) NOT NULL,
  `user_remark` VARCHAR(255) CHARACTER SET 'utf8' NULL,
  `users_image` VARCHAR(255) NOT NULL,
  `shopcar_id_shopcar` INT NOT NULL,
  `orders_id_orders` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC),
  INDEX `fk_users_shopcar1_idx` (`shopcar_id_shopcar` ASC),
  INDEX `fk_users_orders1_idx` (`orders_id_orders` ASC),
  CONSTRAINT `fk_users_shopcar1`
    FOREIGN KEY (`shopcar_id_shopcar`)
    REFERENCES `ssm`.`shopcar` (`id_shopcar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_orders1`
    FOREIGN KEY (`orders_id_orders`)
    REFERENCES `ssm`.`orders` (`id_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssm`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`goods` ;

CREATE TABLE IF NOT EXISTS `ssm`.`goods` (
  `id_goods` INT NOT NULL AUTO_INCREMENT,
  `goods_name` VARCHAR(255) NOT NULL,
  `goods_price` INT NOT NULL,
  `goods_num` INT NOT NULL DEFAULT 1,
  `goods_comment` VARCHAR(100) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`id_goods`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ssm`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`manager` ;

CREATE TABLE IF NOT EXISTS `ssm`.`manager` (
  `id_manager` INT NOT NULL AUTO_INCREMENT,
  `manager_name` VARCHAR(45) NOT NULL,
  `manager_password` VARCHAR(45) NOT NULL,
  `manager_image` VARCHAR(255) NOT NULL,
  `manager_remark` VARCHAR(255) CHARACTER SET 'utf8mb4' NULL,
  PRIMARY KEY (`id_manager`),
  UNIQUE INDEX `manager_name_UNIQUE` (`manager_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `ssm`.`users_has_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`users_has_goods` ;

CREATE TABLE IF NOT EXISTS `ssm`.`users_has_goods` (
  `users_id_user` INT NOT NULL,
  `goods_id_goods` INT NOT NULL,
  PRIMARY KEY (`users_id_user`, `goods_id_goods`),
  INDEX `fk_users_has_goods_goods1_idx` (`goods_id_goods` ASC),
  INDEX `fk_users_has_goods_users_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_users_has_goods_users`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `ssm`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_goods_goods1`
    FOREIGN KEY (`goods_id_goods`)
    REFERENCES `ssm`.`goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssm`.`orders_has_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`orders_has_manager` ;

CREATE TABLE IF NOT EXISTS `ssm`.`orders_has_manager` (
  `orders_id_orders` INT NOT NULL,
  `manager_id_manager` INT NOT NULL,
  PRIMARY KEY (`orders_id_orders`, `manager_id_manager`),
  INDEX `fk_orders_has_manager_manager1_idx` (`manager_id_manager` ASC),
  INDEX `fk_orders_has_manager_orders1_idx` (`orders_id_orders` ASC),
  CONSTRAINT `fk_orders_has_manager_orders1`
    FOREIGN KEY (`orders_id_orders`)
    REFERENCES `ssm`.`orders` (`id_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_manager_manager1`
    FOREIGN KEY (`manager_id_manager`)
    REFERENCES `ssm`.`manager` (`id_manager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssm`.`goods_has_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`goods_has_manager` ;

CREATE TABLE IF NOT EXISTS `ssm`.`goods_has_manager` (
  `goods_id_goods` INT NOT NULL,
  `manager_id_manager` INT NOT NULL,
  PRIMARY KEY (`goods_id_goods`, `manager_id_manager`),
  INDEX `fk_goods_has_manager_manager1_idx` (`manager_id_manager` ASC),
  INDEX `fk_goods_has_manager_goods1_idx` (`goods_id_goods` ASC),
  CONSTRAINT `fk_goods_has_manager_goods1`
    FOREIGN KEY (`goods_id_goods`)
    REFERENCES `ssm`.`goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_has_manager_manager1`
    FOREIGN KEY (`manager_id_manager`)
    REFERENCES `ssm`.`manager` (`id_manager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssm`.`users_has_manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`users_has_manager` ;

CREATE TABLE IF NOT EXISTS `ssm`.`users_has_manager` (
  `users_id_user` INT NOT NULL,
  `manager_id_manager` INT NOT NULL,
  PRIMARY KEY (`users_id_user`, `manager_id_manager`),
  INDEX `fk_users_has_manager_manager1_idx` (`manager_id_manager` ASC),
  INDEX `fk_users_has_manager_users1_idx` (`users_id_user` ASC),
  CONSTRAINT `fk_users_has_manager_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `ssm`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_manager_manager1`
    FOREIGN KEY (`manager_id_manager`)
    REFERENCES `ssm`.`manager` (`id_manager`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssm`.`shopcar_has_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`shopcar_has_goods` ;

CREATE TABLE IF NOT EXISTS `ssm`.`shopcar_has_goods` (
  `shopcar_id_shopcar` INT NOT NULL,
  `goods_id_goods` INT NOT NULL,
  PRIMARY KEY (`shopcar_id_shopcar`, `goods_id_goods`),
  INDEX `fk_shopcar_has_goods_goods1_idx` (`goods_id_goods` ASC),
  INDEX `fk_shopcar_has_goods_shopcar1_idx` (`shopcar_id_shopcar` ASC),
  CONSTRAINT `fk_shopcar_has_goods_shopcar1`
    FOREIGN KEY (`shopcar_id_shopcar`)
    REFERENCES `ssm`.`shopcar` (`id_shopcar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopcar_has_goods_goods1`
    FOREIGN KEY (`goods_id_goods`)
    REFERENCES `ssm`.`goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssm`.`goods_has_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssm`.`goods_has_orders` ;

CREATE TABLE IF NOT EXISTS `ssm`.`goods_has_orders` (
  `goods_id_goods` INT NOT NULL,
  `orders_id_orders` INT NOT NULL,
  PRIMARY KEY (`goods_id_goods`, `orders_id_orders`),
  INDEX `fk_goods_has_orders_orders1_idx` (`orders_id_orders` ASC),
  INDEX `fk_goods_has_orders_goods1_idx` (`goods_id_goods` ASC),
  CONSTRAINT `fk_goods_has_orders_goods1`
    FOREIGN KEY (`goods_id_goods`)
    REFERENCES `ssm`.`goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goods_has_orders_orders1`
    FOREIGN KEY (`orders_id_orders`)
    REFERENCES `ssm`.`orders` (`id_orders`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
